# Eventalign_collapse usage

## Bash command line usage

#### From an existing nanopolish eventalign output to a file

In [10]:
%%bash
source ~/.bashrc && workon Nanopolish_0.10.1

NanopolishComp Eventalign_collapse -i ./data/nanopolish_reads.tsv -o ./output/nanopolish_collapsed_reads.tsv
head ./output/nanopolish_collapsed_reads.tsv
head ./output/nanopolish_collapsed_reads.tsv.idx

#0	YGR240C
ref_pos	ref_kmer	num_events	dwell_time	NNNNN_dwell_time	mismatch_dwell_time
1656	GAAAA	1	0.00266	0.0	0.0
1657	AAAAC	1	0.00764	0.0	0.0
1658	AAACA	1	0.00398	0.0	0.0
1659	AACAA	1	0.00432	0.0	0.0
1660	ACAAA	1	0.00498	0.0	0.0
1661	CAAAG	1	0.00564	0.0	0.0
1662	AAAGA	1	0.00963	0.0	0.0
1663	AAGAT	1	0.00299	0.0	0.0
ref_id	ref_start	ref_end	read_id	dwell_time	kmers	NNNNN_kmers	mismatch_kmers	missing_kmers	byte_offset	byte_len
YGR240C	1656	2960	0	13.788570000000009	1250	35	0	54	0	38028
YCR030C	1578	2576	1	11.487010000000005	971	23	0	27	38029	29704
YHR174W	0	839	2	9.659210000000002	825	15	0	14	67734	24231
YHR174W	218	1309	3	11.06325000000001	1028	36	0	63	91966	30801
YHR174W	462	1309	4	10.73776000000001	818	18	0	29	122768	24589
YLR441C	173	764	5	5.556939999999999	554	20	0	37	147358	16437
YGR192C	1	989	6	11.731470000000003	927	37	0	61	163796	27388
YDR500C	9	252	8	2.9179100000000027	231	7	0	14	191185	6751
YGR192C	3	995	7	12.30464000000001	946	31	0	50	197937	28123

[Eventalign_collapse] total reads: 21 [114.09 reads/s]

#### From standard input to a file

In [11]:
%%bash
source ~/.bashrc && workon Nanopolish_0.10.1

cat ./data/nanopolish_reads_index.tsv | NanopolishComp Eventalign_collapse -o ./output/nanopolish_collapsed_reads.tsv --verbose
head ./output/nanopolish_collapsed_reads.tsv
head ./output/nanopolish_collapsed_reads.tsv.idx

#0	YGR240C
ref_pos	ref_kmer	num_events	dwell_time	NNNNN_dwell_time	mismatch_dwell_time	start_idx	end_idx
1656	GAAAA	1	0.00266	0.0	0.0	63446	63454
1657	AAAAC	1	0.00764	0.0	0.0	63423	63446
1658	AAACA	1	0.00398	0.0	0.0	63411	63423
1659	AACAA	1	0.00432	0.0	0.0	63398	63411
1660	ACAAA	1	0.00498	0.0	0.0	63383	63398
1661	CAAAG	1	0.00564	0.0	0.0	63366	63383
1662	AAAGA	1	0.00963	0.0	0.0	63337	63366
1663	AAGAT	1	0.00299	0.0	0.0	63328	63337
ref_id	ref_start	ref_end	read_id	dwell_time	kmers	NNNNN_kmers	mismatch_kmers	missing_kmers	byte_offset	byte_len
YGR240C	1656	2960	0	13.788570000000009	1250	35	0	54	0	53046
YCR030C	1578	2576	1	11.487010000000005	971	23	0	27	53047	41374
YHR174W	0	839	2	9.659210000000002	825	15	0	14	94422	33595
YHR174W	218	1309	3	11.06325000000001	1028	36	0	63	128018	43155
YLR441C	173	764	5	5.556939999999999	554	20	0	37	171174	23103
YHR174W	462	1309	4	10.73776000000001	818	18	0	29	194278	34423
YGR192C	1	989	6	11.731470000000003	927	37	0	61	228702	38529
YDR500C	9	252	8	2.9179100000000027	231	7	0	14	267232	9541
YGR192C	3	995	7	12.30464000000001	946	31	0	50	276774	39493

Collapse file by read_id/ref_id
21 reads [00:00, 79.46 reads/s]
[Eventalign_collapse] total reads: 21 [100.28 reads/s]

#### On the fly, from nanopolish eventalign to a file

In [12]:
%%bash
source ~/.bashrc && workon Nanopolish_0.10.1

nanopolish eventalign -t 4 --samples --scale-events --print-read-name --reads ./data/reads.fastq --bam ./data/aligned_reads.bam --genome ./data/reference.fa | NanopolishComp Eventalign_collapse  -o ./output/nanopolish_collapsed_reads.tsv
head ./output/nanopolish_collapsed_reads.tsv
head ./output/nanopolish_collapsed_reads.tsv.idx

#3784283c-47cc-48ac-8d7b-7efd32123b56	YHR174W
ref_pos	ref_kmer	num_events	dwell_time	NNNNN_dwell_time	mismatch_dwell_time	mean	median	num_signals
0	ATGGC	1	0.01096	0.0	0.0	86.3893051147461	85.67970275878906	33
1	TGGCT	4	0.03253	0.0	0.0	104.78181457519531	106.18900299072266	98
2	GGCTG	1	0.00465	0.0	0.0	96.55765533447266	97.75244903564453	14
3	GCTGT	5	0.0385	0.0	0.0	81.69342803955078	80.29779815673828	116
4	CTGTC	1	0.00232	0.0	0.0	102.4487075805664	103.57099914550781	7
5	TGTCT	4	0.019249999999999996	0.0	0.0	107.04158020019531	107.64350128173828	58
6	GTCTC	2	0.00797	0.0	0.0	76.83718872070312	76.87960052490234	24
7	TCTCT	1	0.00232	0.0	0.0	80.0484619140625	80.00689697265625	7
ref_id	ref_start	ref_end	read_id	dwell_time	kmers	NNNNN_kmers	mismatch_kmers	missing_kmers	byte_offset	byte_len
YHR174W	0	839	3784283c-47cc-48ac-8d7b-7efd32123b56	9.659210000000002	825	15	0	14	0	56569
YHR174W	218	1309	3e81c32a-f2ee-4719-a88d-e0affe93d26f	11.06325000000001	1028	36	0	63	56570	71162
YGR240C	1656	2960	97205d42-93ac-4c99-af78-e553f7d1ff83	13.788570000000009	1250	35	0	54	127733	87020
YCR030C	1578	2576	9a1c5296-2ab1-4abd-8d50-e059754cf332	11.487010000000005	971	23	0	27	214754	67812
YLR441C	173	764	6af04302-04c8-4d8d-8e87-aa69178b3f24	5.556939999999999	554	20	0	37	282567	38236
YGR192C	3	995	2c32553e-62c6-4c7a-bf05-249771364f04	12.30464000000001	946	31	0	50	320804	65284
YHR174W	462	1309	0ef36fa0-7c3f-47f5-8410-027f50724701	10.73776000000001	818	18	0	29	386089	56957
YDR500C	9	252	e6a8e4d0-7b3c-471a-be26-fa7857d12663	2.9179100000000027	231	7	0	14	443047	15870
YGR192C	1	989	4e21bf07-e2df-42d8-b347-59ef2c0618ea	11.731470000000003	927	37	0	61	458918	63700

[post-run summary] total reads: 21, unparseable: 0, qc fail: 0, could not calibrate: 0, no alignment: 0, bad fast5: 0
[Eventalign_collapse] total reads: 21 [15.28 reads/s]

## Python API usage

#### Import the package

In [13]:
from NanopolishComp.Eventalign_collapse import Eventalign_collapse

#### Example with minimal file

In [14]:
input_fn = "./data/nanopolish_reads.tsv"
output_fn = "./output/collapsed_nanopolish.tsv"
index_fn = "./output/collapsed_nanopolish.tsv.idx"

Eventalign_collapse (input_fn=input_fn, output_fn=output_fn, threads=6, verbose=True)

print ("Collapsed eventalign file")
! head {output_fn} -n 10

print ("Index file")
! head {index_fn} -n 10

Collapse file by read_id/ref_id
21 reads [00:00, 104.78 reads/s]
[Eventalign_collapse] total reads: 21 [99.0 reads/s]

Collapsed eventalign file
#0	YGR240C
ref_pos	ref_kmer	num_events	dwell_time	NNNNN_dwell_time	mismatch_dwell_time
1656	GAAAA	1	0.00266	0.0	0.0
1657	AAAAC	1	0.00764	0.0	0.0
1658	AAACA	1	0.00398	0.0	0.0
1659	AACAA	1	0.00432	0.0	0.0
1660	ACAAA	1	0.00498	0.0	0.0
1661	CAAAG	1	0.00564	0.0	0.0
1662	AAAGA	1	0.00963	0.0	0.0
1663	AAGAT	1	0.00299	0.0	0.0
Index file
ref_id	ref_start	ref_end	read_id	dwell_time	kmers	NNNNN_kmers	mismatch_kmers	missing_kmers	byte_offset	byte_len
YGR240C	1656	2960	0	13.788570000000009	1250	35	0	54	0	38028
YCR030C	1578	2576	1	11.487010000000005	971	23	0	27	38029	29704
YHR174W	0	839	2	9.659210000000002	825	15	0	14	67734	24231
YHR174W	218	1309	3	11.06325000000001	1028	36	0	63	91966	30801
YLR441C	173	764	5	5.556939999999999	554	20	0	37	122768	16437
YHR174W	462	1309	4	10.73776000000001	818	18	0	29	139206	24589
YGR192C	1	989	6	11.731470000000003	927	37	0	61	163796	27388
YDR500C	9	252	8	2.9179100000000027	231	7	0	14	191185	6751
YGR192C	3	995	7	12.30464000000001	946	31	0	50	197937	28123

#### Example with indexes

In [15]:
input_fn = "./data/nanopolish_reads_index.tsv"
output_fn = "./output/collapsed_nanopolish_index.tsv"
index_fn = "./output/collapsed_nanopolish_index.tsv.idx"

Eventalign_collapse (input_fn=input_fn, output_fn=output_fn, verbose=True, threads=6)

print ("\nCollapsed eventalign file")
! head {output_fn} -n 10

print ("\nIndex file")
! head {index_fn} -n 10

Collapse file by read_id/ref_id
21 reads [00:00, 87.09 reads/s]
[Eventalign_collapse] total reads: 21 [80.04 reads/s]

Collapsed eventalign file
#0	YGR240C
ref_pos	ref_kmer	num_events	dwell_time	NNNNN_dwell_time	mismatch_dwell_time	start_idx	end_idx
1656	GAAAA	1	0.00266	0.0	0.0	63446	63454
1657	AAAAC	1	0.00764	0.0	0.0	63423	63446
1658	AAACA	1	0.00398	0.0	0.0	63411	63423
1659	AACAA	1	0.00432	0.0	0.0	63398	63411
1660	ACAAA	1	0.00498	0.0	0.0	63383	63398
1661	CAAAG	1	0.00564	0.0	0.0	63366	63383
1662	AAAGA	1	0.00963	0.0	0.0	63337	63366
1663	AAGAT	1	0.00299	0.0	0.0	63328	63337

Index file
ref_id	ref_start	ref_end	read_id	dwell_time	kmers	NNNNN_kmers	mismatch_kmers	missing_kmers	byte_offset	byte_len
YGR240C	1656	2960	0	13.788570000000009	1250	35	0	54	0	53046
YHR174W	0	839	2	9.659210000000002	825	15	0	14	53047	33595
YCR030C	1578	2576	1	11.487010000000005	971	23	0	27	86643	41374
YHR174W	218	1309	3	11.06325000000001	1028	36	0	63	128018	43155
YHR174W	462	1309	4	10.73776000000001	818	18	0	29	171174	34423
YLR441C	173	764	5	5.556939999999999	554	20	0	37	205598	23103
YGR192C	1	989	6	11.731470000000003	927	37	0	61	228702	38529
YDR500C	9	252	8	2.9179100000000027	231	7	0	14	267232	9541
YGR192C	3	995	7	12.30464000000001	946	31	0	50	276774	39493

#### Example including samples

In [16]:
input_fn = "./data/nanopolish_reads_samples.tsv"
output_fn = "./output/collapsed_nanopolish_samples.tsv"
index_fn = "./output/collapsed_nanopolish_samples.tsv.idx"

Eventalign_collapse (input_fn=input_fn, output_fn=output_fn, verbose=True, threads=6, stat_fields=["mean", "std", "median", "mad", "num_signals"])

print ("\nCollapsed eventalign file")
! head {output_fn} -n 10

print ("\nIndex file")
! head {index_fn} -n 10

Collapse file by read_id/ref_id
21 reads [00:01,  4.21 reads/s]
[Eventalign_collapse] total reads: 21 [13.15 reads/s]

Collapsed eventalign file
#2	YHR174W
ref_pos	ref_kmer	num_events	dwell_time	NNNNN_dwell_time	mismatch_dwell_time	mean	std	median	mad	num_signals
0	ATGGC	1	0.01096	0.0	0.0	86.3893051147461	3.8192403316497803	85.67970275878906	2.618194580078125	33
1	TGGCT	4	0.03253	0.0	0.0	104.78181457519531	6.572873592376709	106.18900299072266	3.9269943237304688	98
2	GGCTG	1	0.00465	0.0	0.0	96.55765533447266	6.874111652374268	97.75244903564453	5.382049560546875	14
3	GCTGT	5	0.0385	0.0	0.0	81.69342803955078	5.14208984375	80.29779815673828	1.5273017883300781	116
4	CTGTC	1	0.00232	0.0	0.0	102.4487075805664	1.5290673971176147	103.57099914550781	0.2910003662109375	7
5	TGTCT	4	0.019249999999999996	0.0	0.0	107.04158020019531	5.813553810119629	107.64350128173828	2.5454978942871094	58
6	GTCTC	2	0.00797	0.0	0.0	76.83718872070312	2.1963260173797607	76.87960052490234	1.1636505126953125	24
7	TCTCT	1	0.00232	0.0	0.0	80.0484619140625	1.0306347608566284	80.00689697265625	0.727294921875	7

Index file
ref_id	ref_start	ref_end	read_id	dwell_time	kmers	NNNNN_kmers	mismatch_kmers	missing_kmers	byte_offset	byte_len
YHR174W	0	839	2	9.659210000000002	825	15	0	14	0	86998
YGR240C	1656	2960	0	13.788570000000009	1250	35	0	54	86999	133270
YCR030C	1578	2576	1	11.487010000000005	971	23	0	27	220270	103547
YHR174W	218	1309	3	11.06325000000001	1028	36	0	63	323818	108951
YLR441C	173	764	5	5.556939999999999	554	20	0	37	432770	58654
YDR500C	9	252	8	2.9179100000000027	231	7	0	14	491425	24391
YHR174W	462	1309	4	10.73776000000001	818	18	0	29	515817	86902
YDR224C	0	389	9	4.2840300000000004	376	8	0	13	602720	39471
YGR192C	1	989	6	11.731470000000003	927	37	0	61	642192	97890

#### Example including samples and writing samples values in ouput file

In [17]:
input_fn = "./data/nanopolish_reads_samples.tsv"
output_fn = "./output/collapsed_nanopolish_samples_all.tsv"
index_fn = "./output/collapsed_nanopolish_samples_all.tsv.idx"

Eventalign_collapse (input_fn=input_fn, output_fn=output_fn, verbose=True, threads=6, write_samples=True)

print ("\nCollapsed eventalign file")
! head {output_fn} -n 10

print ("\nIndex file")
! head {index_fn} -n 10

Collapse file by read_id/ref_id
21 reads [00:00, 24.38 reads/s]
[Eventalign_collapse] total reads: 21 [23.73 reads/s]

Collapsed eventalign file
#1	YCR030C
ref_pos	ref_kmer	num_events	dwell_time	NNNNN_dwell_time	mismatch_dwell_time	mean	median	num_signals	samples
1578	CCACC	1	0.00365	0.0	0.0	70.06341552734375	70.67729949951172	11	70.6773,72.1454,71.4114,63.6306,69.2093,69.2093,67.3008,72.5858,69.9433,72.8794,71.705
1579	CACCC	15	0.09761000000000002	0.0	0.0	74.59468841552734	75.08149719238281	294	75.0815,75.8156,79.6326,78.0177,75.3752,77.2837,78.0177,72.2922,76.99,74.7879,75.3752,75.522,75.6688,73.3199,74.9347,77.5773,73.7603,74.3475,72.7326,75.522,77.2837,75.2284,76.6964,78.4581,78.4581,79.7794,76.5496,76.8432,70.2369,70.2369,81.1006,77.8709,74.9347,72.439,75.8156,77.5773,75.9624,77.4305,76.1092,77.2837,64.5114,74.4943,78.4581,77.4305,76.8432,75.0815,76.1092,78.3113,76.5496,75.6688,76.5496,77.4305,78.6049,76.4028,75.8156,77.1368,71.8518,76.4028,75.8156,75.9624,74.9347,78.3113,72.2922,75.6688,75.0815,75.522,75.9624,70.6773,69.9433,69.2093,68.3284,69.3561,69.2093,69.7965,67.888,68.9157,68.622,69.0625,69.7965,73.173,76.1092,74.7879,75.2284,78.3113,76.256,78.3113,77.7241,72.7326,73.6135,78.6049,75.522,75.8156,74.0539,67.3008,72.439,72.2922,67.0072,74.6411,76.1092,75.8156,73.3199,77.2837,70.3837,73.4667,74.7879,76.6964,79.1921,73.3199,76.6964,76.4028,71.1178,76.1092,79.7794,77.7241,77.1368,74.3475,78.6049,78.8985,77.2837,77.7241,70.0901,79.0453,76.1092,73.6135,78.1645,79.0453,75.8156,79.3389,79.0453,77.1368,78.1645,78.3113,77.8709,79.4858,75.8156,76.4028,77.2837,77.4305,79.6326,77.4305,81.8347,76.5496,76.5496,78.8985,74.7879,77.2837,80.2198,75.6688,78.1645,76.99,79.3389,79.0453,71.5582,78.6049,79.7794,78.3113,78.1645,75.3752,76.8432,80.073,78.3113,80.2198,80.073,80.9538,77.5773,77.8709,75.6688,80.807,77.8709,78.0177,79.3389,80.2198,80.2198,76.1092,77.8709,76.5496,76.6964,77.8709,77.1368,75.9624,76.99,72.2922,71.8518,73.9071,68.9157,70.0901,71.8518,75.3752,73.9071,72.1454,73.6135,74.4943,73.173,75.9624,75.0815,74.6411,75.0815,75.2284,74.4943,75.522,76.6964,72.7326,73.7603,74.9347,75.522,74.0539,71.2646,70.3837,72.439,75.522,75.9624,71.705,72.2922,70.8241,71.1178,70.971,74.7879,75.6688,74.6411,72.1454,73.0262,71.4114,73.9071,74.2007,75.0815,74.4943,72.1454,72.8794,72.1454,69.6497,71.5582,72.439,70.6773,69.7965,68.4752,68.7689,73.6135,73.7603,72.2922,71.4114,69.2093,70.2369,73.3199,72.439,71.5582,67.4476,72.8794,72.2922,72.5858,72.439,73.9071,69.6497,72.2922,73.6135,74.4943,73.0262,70.0901,72.439,71.8518,72.1454,71.9986,70.2369,74.0539,70.971,72.1454,71.2646,71.8518,71.1178,71.5582,70.971,69.2093,70.8241,71.4114,71.2646,72.1454,70.5305,69.6497,70.6773,69.9433,72.8794,67.5944,66.7135,70.5305,69.7965,68.622,73.4667,73.7603,76.1092,77.1368,74.3475,75.8156,74.7879,76.8432,75.8156
1580	ACCCT	1	0.00232	0.0	0.0	67.23785400390625	67.88800048828125	7	64.9519,65.6859,67.888,68.1816,68.1816,65.6859,70.0901
1581	CCCTC	1	0.00232	0.0	0.0	72.0615005493164	72.58580017089844	7	70.3837,72.5858,70.6773,71.4114,73.0262,73.6135,72.7326
1582	CCTCA	5	0.0156	0.0	0.0	73.5634994506836	73.76029968261719	47	75.522,77.8709,75.2284,74.3475,75.9624,76.6964,72.1454,71.1178,71.1178,72.439,76.256,74.0539,73.0262,73.4667,70.6773,71.5582,69.7965,71.1178,68.3284,70.6773,73.6135,69.6497,67.4476,73.7603,74.3475,72.8794,74.0539,73.3199,74.4943,75.522,72.8794,72.5858,71.2646,73.4667,74.3475,74.4943,74.9347,71.9986,72.2922,76.8432,74.9347,76.5496,75.6688,75.2284,75.0815,76.6964,77.7241
1583	CTCAA	1	0.00398	0.0	0.0	77.58948516845703	78.16450500488281	12	74.3475,75.0815,78.3113,78.8985,77.8709,78.3113,76.4028,78.0177,77.1368,78.3113,78.8985,79.4858
1584	TCAAG	1	0.01096	0.0	0.0	83.52072143554688	84.03679656982422	33	88.441,79.9262,81.6879,81.9815,85.0644,86.9729,84.624,81.1006,76.99,79.0453,79.9262,84.0368,92.1112,83.0091,84.1836,80.807,84.0368,85.7985,87.2665,85.6516,83.0091,87.7069,81.2474,84.0368,79.1921,79.6326,87.2665,83.4495,84.0368,83.7432,80.807,84.624,84.7708
1585	CAAGG	1	0.00232	0.0	0.0	105.23970794677734	104.2959976196289	7	113.251,102.534,104.296,103.415,106.498,101.36,105.324

Index file
ref_id	ref_start	ref_end	read_id	dwell_time	kmers	NNNNN_kmers	mismatch_kmers	missing_kmers	byte_offset	byte_len
YCR030C	1578	2576	1	11.487010000000005	971	23	0	27	0	340556
YGR240C	1656	2960	0	13.788570000000009	1250	35	0	54	340557	414726
YHR174W	0	839	2	9.659210000000002	825	15	0	14	755284	286563
YHR174W	218	1309	3	11.06325000000001	1028	36	0	63	1041848	334302
YLR441C	173	764	5	5.556939999999999	554	20	0	37	1376151	170217
YHR174W	462	1309	4	10.73776000000001	818	18	0	29	1546369	312548
YDR500C	9	252	8	2.9179100000000027	231	7	0	14	1858918	85265
YDR224C	0	389	9	4.2840300000000004	376	8	0	13	1944184	127493
YGR192C	1	989	6	11.731470000000003	927	37	0	61	2071678	342092

#### Using the index to random access a specific entry in the file

In [18]:
output_fn = "./output/collapsed_nanopolish_samples.tsv"
index_fn = "./output/collapsed_nanopolish_samples.tsv.idx"

# Import the index in a pandas dataframe (because it is simple)
import pandas as pd 
index_df = pd.read_table (index_fn)

# Select random lines
random_lines = index_df.sample(5)
print ("Random index lines")
display (random_lines)

# Open the collapsed event align file
with open (output_fn) as fp:
    for id, read in random_lines.iterrows():
        
        # Access the header corresponding to the randomly selected index line using seek 
        fp.seek(0) # Return to file start
        fp.seek(read.byte_offset) # Move to the offset indicated in the index file
        print (fp.readline().rstrip()) # Print read header
        df = pd.read_table (fp, nrows=read.kmers) # Read lines corresponding to the read
        with pd.option_context("display.max_rows",4): # display first and last lines
            display(df)

Random index lines

,ref_id,ref_start,ref_end,read_id,dwell_time,kmers,NNNNN_kmers,mismatch_kmers,missing_kmers,byte_offset,byte_len
17,YEL052W,1095,1521,17,5.93670,407,11,0,19,1194814,43713
15,YLR110C,14,395,15,4.61444,364,9,0,17,1138139,38187
7,YDR224C,0,389,9,4.28403,376,8,0,13,602720,39471
0,YHR174W,0,839,2,9.65921,825,15,0,14,0,86998
1,YGR240C,1656,2960,0,13.78857,1250,35,0,54,86999,133270

#17	YEL052W

,ref_pos,ref_kmer,num_events,dwell_time,NNNNN_dwell_time,mismatch_dwell_time,mean,std,median,mad,num_signals
0,1095,CAGTT,1,0.00598,0.00598,0.0,101.852730,3.999981,100.642502,2.122303,18
1,1098,TTGTG,8,0.09694,0.00000,0.0,104.335045,5.868126,104.390999,3.960999,292
...,...,...,...,...,...,...,...,...,...,...,...
405,1519,CTACA,12,0.06041,0.00000,0.0,81.252815,1.824221,81.048401,1.273251,182
406,1520,TACAT,12,0.06009,0.00000,0.0,88.112602,4.875258,86.848701,2.263504,181

#15	YLR110C

,ref_pos,ref_kmer,num_events,dwell_time,NNNNN_dwell_time,mismatch_dwell_time,mean,std,median,mad,num_signals
0,14,TGTCG,2,0.00598,0.0,0.0,105.332932,7.113524,105.947998,5.534996,18
1,15,GTCGC,1,0.00730,0.0,0.0,79.745407,1.910044,80.000298,1.365601,22
...,...,...,...,...,...,...,...,...,...,...,...
362,393,TTGTT,7,0.04217,0.0,0.0,97.856377,7.673260,99.407097,4.743904,127
363,394,TGTTG,5,0.01859,0.0,0.0,96.470421,13.139284,90.566200,4.959553,56

#9	YDR224C

,ref_pos,ref_kmer,num_events,dwell_time,NNNNN_dwell_time,mismatch_dwell_time,mean,std,median,mad,num_signals
0,0,ATGTC,1,0.00299,0.0,0.0,93.983742,1.811953,94.572502,1.115601,9
1,1,TGTCT,1,0.00498,0.0,0.0,100.615280,12.008626,95.409203,11.434799,15
...,...,...,...,...,...,...,...,...,...,...,...
374,387,CAAGC,11,0.04947,0.0,0.0,102.050323,9.757517,103.218002,8.227997,149
375,388,AAGCA,1,0.00764,0.0,0.0,80.251816,3.183472,79.512100,2.510101,23

#2	YHR174W

,ref_pos,ref_kmer,num_events,dwell_time,NNNNN_dwell_time,mismatch_dwell_time,mean,std,median,mad,num_signals
0,0,ATGGC,1,0.01096,0.00000,0.0,86.389305,3.819240,85.679703,2.618195,33
1,1,TGGCT,4,0.03253,0.00000,0.0,104.781815,6.572874,106.189003,3.926994,98
...,...,...,...,...,...,...,...,...,...,...,...
823,837,GCTGA,3,0.01395,0.00000,0.0,90.593964,6.167919,90.479698,4.945454,42
824,838,CTGAC,6,0.04782,0.01727,0.0,97.368584,17.856701,94.988754,16.291100,144

#0	YGR240C

,ref_pos,ref_kmer,num_events,dwell_time,NNNNN_dwell_time,mismatch_dwell_time,mean,std,median,mad,num_signals
0,1656,GAAAA,1,0.00266,0.0,0.0,105.497749,1.198813,105.480003,0.852997,8
1,1657,AAAAC,1,0.00764,0.0,0.0,111.092743,1.667485,111.025002,0.995003,23
...,...,...,...,...,...,...,...,...,...,...,...
1248,2958,AAATG,2,0.01826,0.0,0.0,108.238159,9.100697,107.897003,6.398003,55
1249,2959,AATGA,1,0.00332,0.0,0.0,84.509178,3.165896,84.367004,1.919350,10